### ISSUE TITLE
Duplicate AttributeOption raises MultipleObjectsReturned on Product save

### ISSUE THREAD

**Issue by john-parton** [django-oscar/django-oscar#1935]
If you create two `AttributeOption` instances with both option values as `Large` and then attempt to save the product, you get a `MultipleObjectsReturned` exception.

The most straightforward fix is to simply add a `unique_together` for `AttributeOption.group` and `AttributeOption.option`. I'll submit a PR soon.

``` python
In [1]: product = Product.objects.filter(product_class__name="T-shirt")[0]

In [2]: product.attr.size = 'Large'

In [3]: product.save()
---------------------------------------------------------------------------
MultipleObjectsReturned                   Traceback (most recent call last)
<ipython-input-3-c3e25804d473> in <module>()
----> 1 product.save()

/home/john/Code/projects/pillowcentral/django-oscar/src/oscar/apps/catalogue/abstract_models.pyc in save(self, *args, **kwargs)
    440             self.slug = slugify(self.get_title())
    441         super(AbstractProduct, self).save(*args, **kwargs)
--> 442         self.attr.save()
    443 
    444     # Properties

/home/john/Code/projects/pillowcentral/django-oscar/src/oscar/apps/catalogue/abstract_models.pyc in save(self)
    766             if hasattr(self, attribute.code):
    767                 value = getattr(self, attribute.code)
--> 768                 attribute.save_value(self.product, value)
    769 
    770 

/home/john/Code/projects/pillowcentral/django-oscar/src/oscar/apps/catalogue/abstract_models.pyc in save_value(self, product, value)
    872                 return
    873             if value != value_obj.value:
--> 874                 value_obj.value = value
    875                 value_obj.save()
    876 

/home/john/Code/projects/pillowcentral/django-oscar/src/oscar/apps/catalogue/abstract_models.pyc in _set_value(self, new_value)
    974             # Need to look up instance of AttributeOption
    975             new_value = self.attribute.option_group.options.get(
--> 976                 option=new_value)
    977         setattr(self, 'value_%s' % self.attribute.type, new_value)
    978 

/home/john/Code/venv/oscar/local/lib/python2.7/site-packages/django/db/models/manager.pyc in manager_method(self, *args, **kwargs)
    125         def create_method(name, method):
    126             def manager_method(self, *args, **kwargs):
--> 127                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    128             manager_method.__name__ = method.__name__
    129             manager_method.__doc__ = method.__doc__

/home/john/Code/venv/oscar/local/lib/python2.7/site-packages/django/db/models/query.pyc in get(self, *args, **kwargs)
    336         raise self.model.MultipleObjectsReturned(
    337             "get() returned more than one %s -- it returned %s!" %
--> 338             (self.model._meta.object_name, num)
    339         )
    340 

MultipleObjectsReturned: get() returned more than one AttributeOption -- it returned 2!
```

**Comment by maikhoepfel** [comment]
Fixed by https://github.com/django-oscar/django-oscar/issues/1936

**Comment by sasha0** [comment]
Does the issue still occur? If not, I suppose it could be closed.

**Comment by john-parton** [comment]
We might be waiting on documentation. My PR didn't include it.

**Comment by solarissmoke** [comment]
Fixed in #1936.
